services:
  - type: web
    name: PiroAutoFilterBot
    runtime: python
    plan: free
    region: oregon
    buildCommand: pip install -U -r requirements.txt
    startCommand: python3 bot.py
    envVars:
      - key: API_ID
        value: "22417964"
      - key: API_HASH
        value: "153755c2bd889b23a9d9e73dc01afc49"
      - key: BOT_TOKEN
        value: "8508633803:AAE3N5be7fx4aNsCNKhZph-DhUiq6SuJQbU"
      - key: DATABASE_URI
        value: "mongodb+srv://ali:Ali2026Pass@cluster0.esdu8gs.mongodb.net/?appName=Cluster0&tlsAllowInvalidCertificates=true"
      - key: DATABASE_NAME
        value: "Scottbot"
      - key: ADMINS
        value: "7124506900"
      - key: LOG_CHANNEL
        value: "7124506900"
      - key: CHANNELS
        value: "7124506900"
